export default {
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
  SIGN_IN_REQUEST: '@AUTH/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: '@AUTH/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: '@AUTH/SIGN_IN_FAILURE',
  SIGN_OUT_REQUEST: '@AUTH/SIGN_OUT_REQUEST',
};
