export default {
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
  MESSAGES_REQUEST: '@MESSAGES/MESSAGES_REQUEST',
  MESSAGES_SUCCESS: '@MESSAGES/MESSAGES_SUCCESS',
  PUSH_MESSAGE_REQUEST: '@MESSAGES/PUSH_MESSAGE_REQUEST',
};
